# Site settings
title: Jacob Walker
email: jacob.walker94@gmail.com
description: Just another homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ja.co.bw" # the base hostname & protocol for your site
twitter_username: jacobwalkr
github_username:  jacobwalkr

# Build settings
markdown: kramdown

sass:
    style: :compressed

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            permalink: date
            is_post: true # flag for posts - used in layout
